layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

exclude:
  - README.md
  - Gemfile

projects:
  sort_by: pushed
  limit: 21
  exclude:
    archived: false
    forks: false
    projects:

social_media:
  facebook: d.woffinden
  keybase: dwoffinden
  linkedin: danielwoffinden
  # hackerrank: your_username
  # instagram: your_username
  # mastodon: your_username
  # stackoverflow: your_user_id
  # twitter: your_username
  # website: http://your_website_url
  # youtube: your_username

