layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

# https://jekyllrb.com/docs/troubleshooting/#configuration-problems
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - gemset.nix
  - shell.nix
  - CNAME

social_media:
  facebook: d.woffinden
  keybase: dwoffinden
  linkedin: danielwoffinden
  matrix: dwoffinden:matrix.org
  stackoverflow: 2125397
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # instagram: your_username
  # mastodon: your_username
  # medium: your_username
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

sass:
  style: compressed
  # implementation: sass-embedded
  sass_dir: assets/css/
  load_paths:
    - node_modules/
