layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

exclude:
  - README.md
  - Gemfile

social_media:
  facebook: d.woffinden
  keybase: dwoffinden
  linkedin: danielwoffinden
  stackoverflow: 2125397
  # hackerrank: your_username
  # instagram: your_username
  # mastodon: your_username
  # twitter: your_username
  # website: http://your_website_url
  # youtube: your_username

