layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

exclude:
  - README.md
  - Gemfile

projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: d.woffinden
  keybase: dwoffinden
  linkedin: danielwoffinden
  stackoverflow: 2125397
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  # instagram: your_username
  # mastodon: your_username
  # medium: your_username
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

