# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@primer/css-15.2.0" = {
      name = "_at_primer_slash_css";
      packageName = "@primer/css";
      version = "15.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@primer/css/-/css-15.2.0.tgz";
        sha512 = "/vNDchWrxlXqd6E+SWQcChPHJVzGia9aCaTYoz8O9sJTnUSiTKOgSNCQuOXyUInPruTRSqj+z3MZxayKcTsWhA==";
      };
    };
    "@primer/octicons-9.6.0" = {
      name = "_at_primer_slash_octicons";
      packageName = "@primer/octicons";
      version = "9.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@primer/octicons/-/octicons-9.6.0.tgz";
        sha512 = "B5Wzk5izRXXz0JqEXJkVUtqhCXSpUKgqYkVwegMkp5sziBW+ksd9LPbONlCWyyLODwf9GsI2sBXekR7m+JJDBw==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
  };
  args = {
    name = "daw.dev";
    packageName = "daw.dev";
    src = ./.;
    dependencies = [
      sources."@primer/css-15.2.0"
      sources."@primer/octicons-9.6.0"
      sources."object-assign-4.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = { };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
